apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfr-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sfr-ui
  template:
    metadata:
      labels:
        app: sfr-ui
    spec:
      containers:
      - image: https://hub.docker.com/_/node:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
